export interface FeaturedNotebook {
  slug: string;
  titleKey: string;
  descriptionKey: string;
  bgClass: string;
  icon: string;
  author: string;
  date: string;
  sourceCount: number;
  /** Decorative SVG pattern key for the card background */
  pattern: "circles" | "grid" | "waves" | "dots" | "hexagons" | "triangles" | "lines" | "diamond";
  /** Company website domain for logo (Clearbit) */
  website?: string;
  /** Broad category for filtering */
  category: string;
}

export const CATEGORIES = [
  "All",
  "Cybersecurity",
  "AI/ML",
  "DevTools",
  "SaaS",
  "Fintech",
  "E-commerce",
  "Mobility",
  "HealthTech",
] as const;

export const featuredNotebooks: FeaturedNotebook[] = [
  {
    slug: "wix",
    titleKey: "wix",
    descriptionKey: "wixDesc",
    bgClass: "bg-[#191919] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "circles",
    website: "wix.com",
    category: "SaaS",
  },
  {
    slug: "monday-com",
    titleKey: "mondayCom",
    descriptionKey: "mondayComDesc",
    bgClass: "bg-[#CC785C] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "grid",
    website: "monday.com",
    category: "SaaS",
  },
  {
    slug: "jfrog",
    titleKey: "jfrog",
    descriptionKey: "jfrogDesc",
    bgClass: "bg-[#D4A27F] text-[#191919]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "waves",
    website: "jfrog.com",
    category: "DevTools",
  },
  {
    slug: "fiverr",
    titleKey: "fiverr",
    descriptionKey: "fiverrDesc",
    bgClass: "bg-[#40403E] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "dots",
    website: "fiverr.com",
    category: "E-commerce",
  },
  {
    slug: "gong",
    titleKey: "gong",
    descriptionKey: "gongDesc",
    bgClass: "bg-[#FAFAF7] text-[#191919] border border-black/5 dark:bg-[#262626] dark:text-[#FAFAF7] dark:border-white/5",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "hexagons",
    website: "gong.io",
    category: "AI/ML",
  },
  {
    slug: "appsflyer",
    titleKey: "appsflyer",
    descriptionKey: "appsflyerDesc",
    bgClass: "bg-[#262626] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "triangles",
    website: "appsflyer.com",
    category: "SaaS",
  },
  {
    slug: "snyk",
    titleKey: "snyk",
    descriptionKey: "snykDesc",
    bgClass: "bg-[#666666] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "lines",
    website: "snyk.io",
    category: "Cybersecurity",
  },
  {
    slug: "check-point",
    titleKey: "checkPoint",
    descriptionKey: "checkPointDesc",
    bgClass: "bg-[#E5E4DF] text-[#191919] dark:bg-[#40403E] dark:text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "diamond",
    website: "checkpoint.com",
    category: "Cybersecurity",
  },
  {
    slug: "cyberark",
    titleKey: "cyberArk",
    descriptionKey: "cyberArkDesc",
    bgClass: "bg-[#191919] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "circles",
    website: "cyberark.com",
    category: "Cybersecurity",
  },
  {
    slug: "tabnine",
    titleKey: "tabnine",
    descriptionKey: "tabnineDesc",
    bgClass: "bg-[#CC785C] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "grid",
    website: "tabnine.com",
    category: "AI/ML",
  },
  {
    slug: "walkme",
    titleKey: "walkMe",
    descriptionKey: "walkMeDesc",
    bgClass: "bg-[#D4A27F] text-[#191919]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "waves",
    website: "walkme.com",
    category: "SaaS",
  },
  {
    slug: "cloudinary",
    titleKey: "cloudinary",
    descriptionKey: "cloudinaryDesc",
    bgClass: "bg-[#40403E] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "dots",
    website: "cloudinary.com",
    category: "DevTools",
  },
  {
    slug: "redis",
    titleKey: "redis",
    descriptionKey: "redisDesc",
    bgClass: "bg-[#FAFAF7] text-[#191919] border border-black/5 dark:bg-[#262626] dark:text-[#FAFAF7] dark:border-white/5",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "hexagons",
    website: "redis.io",
    category: "DevTools",
  },
  {
    slug: "lightrun",
    titleKey: "lightrun",
    descriptionKey: "lightrunDesc",
    bgClass: "bg-[#262626] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "triangles",
    website: "lightrun.com",
    category: "DevTools",
  },
  {
    slug: "qodo",
    titleKey: "qodo",
    descriptionKey: "qodoDesc",
    bgClass: "bg-[#666666] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "lines",
    website: "qodo.ai",
    category: "AI/ML",
  },
  {
    slug: "prompt-security",
    titleKey: "promptSecurity",
    descriptionKey: "promptSecurityDesc",
    bgClass: "bg-[#E5E4DF] text-[#191919] dark:bg-[#40403E] dark:text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "diamond",
    website: "prompt.security",
    category: "Cybersecurity",
  },
  {
    slug: "armis",
    titleKey: "armis",
    descriptionKey: "armisDesc",
    bgClass: "bg-[#191919] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "circles",
    website: "armis.com",
    category: "Cybersecurity",
  },
  {
    slug: "cato-networks",
    titleKey: "catoNetworks",
    descriptionKey: "catoNetworksDesc",
    bgClass: "bg-[#CC785C] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "grid",
    website: "catonetworks.com",
    category: "Cybersecurity",
  },
  {
    slug: "pentera",
    titleKey: "pentera",
    descriptionKey: "penteraDesc",
    bgClass: "bg-[#D4A27F] text-[#191919]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "waves",
    website: "pentera.io",
    category: "Cybersecurity",
  },
  {
    slug: "silverfort",
    titleKey: "silverfort",
    descriptionKey: "silverfortDesc",
    bgClass: "bg-[#40403E] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "dots",
    website: "silverfort.com",
    category: "Cybersecurity",
  },
  {
    slug: "payoneer",
    titleKey: "payoneer",
    descriptionKey: "payoneerDesc",
    bgClass: "bg-[#FAFAF7] text-[#191919] border border-black/5 dark:bg-[#262626] dark:text-[#FAFAF7] dark:border-white/5",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "hexagons",
    website: "payoneer.com",
    category: "Fintech",
  },
  {
    slug: "melio",
    titleKey: "melio",
    descriptionKey: "melioDesc",
    bgClass: "bg-[#262626] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "triangles",
    website: "meliopayments.com",
    category: "Fintech",
  },
  {
    slug: "tipalti",
    titleKey: "tipalti",
    descriptionKey: "tipaltiDesc",
    bgClass: "bg-[#666666] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "lines",
    website: "tipalti.com",
    category: "Fintech",
  },
  {
    slug: "pagaya",
    titleKey: "pagaya",
    descriptionKey: "pagayaDesc",
    bgClass: "bg-[#E5E4DF] text-[#191919] dark:bg-[#40403E] dark:text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "diamond",
    website: "pagaya.com",
    category: "Fintech",
  },
  {
    slug: "lemonade",
    titleKey: "lemonade",
    descriptionKey: "lemonadeDesc",
    bgClass: "bg-[#191919] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "circles",
    website: "lemonade.com",
    category: "Fintech",
  },
  {
    slug: "yotpo",
    titleKey: "yotpo",
    descriptionKey: "yotpoDesc",
    bgClass: "bg-[#CC785C] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "grid",
    website: "yotpo.com",
    category: "E-commerce",
  },
  {
    slug: "riskified",
    titleKey: "riskified",
    descriptionKey: "riskifiedDesc",
    bgClass: "bg-[#D4A27F] text-[#191919]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "waves",
    website: "riskified.com",
    category: "E-commerce",
  },
  {
    slug: "forter",
    titleKey: "forter",
    descriptionKey: "forterDesc",
    bgClass: "bg-[#40403E] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "dots",
    website: "forter.com",
    category: "E-commerce",
  },
  {
    slug: "dynamic-yield",
    titleKey: "dynamicYield",
    descriptionKey: "dynamicYieldDesc",
    bgClass: "bg-[#FAFAF7] text-[#191919] border border-black/5 dark:bg-[#262626] dark:text-[#FAFAF7] dark:border-white/5",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "hexagons",
    website: "dynamicyield.com",
    category: "E-commerce",
  },
  {
    slug: "coralogix",
    titleKey: "coralogix",
    descriptionKey: "coralogixDesc",
    bgClass: "bg-[#262626] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "triangles",
    website: "coralogix.com",
    category: "DevTools",
  },
  {
    slug: "bigpanda",
    titleKey: "bigPanda",
    descriptionKey: "bigPandaDesc",
    bgClass: "bg-[#666666] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "lines",
    website: "bigpanda.io",
    category: "AI/ML",
  },
  {
    slug: "via",
    titleKey: "via",
    descriptionKey: "viaDesc",
    bgClass: "bg-[#E5E4DF] text-[#191919] dark:bg-[#40403E] dark:text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "diamond",
    website: "ridewithvia.com",
    category: "Mobility",
  },
  {
    slug: "innoviz",
    titleKey: "innoviz",
    descriptionKey: "innovizDesc",
    bgClass: "bg-[#191919] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "circles",
    website: "innoviz.tech",
    category: "Mobility",
  },
  {
    slug: "optibus",
    titleKey: "optibus",
    descriptionKey: "optibusDesc",
    bgClass: "bg-[#CC785C] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "grid",
    website: "optibus.com",
    category: "Mobility",
  },
  {
    slug: "winn-ai",
    titleKey: "winnAi",
    descriptionKey: "winnAiDesc",
    bgClass: "bg-[#D4A27F] text-[#191919]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "waves",
    website: "winn.ai",
    category: "AI/ML",
  },
  {
    slug: "nimble",
    titleKey: "nimble",
    descriptionKey: "nimbleDesc",
    bgClass: "bg-[#40403E] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "dots",
    website: "nimbleway.com",
    category: "SaaS",
  },
  {
    slug: "anima",
    titleKey: "anima",
    descriptionKey: "animaDesc",
    bgClass: "bg-[#FAFAF7] text-[#191919] border border-black/5 dark:bg-[#262626] dark:text-[#FAFAF7] dark:border-white/5",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "hexagons",
    website: "animaapp.com",
    category: "DevTools",
  },
  {
    slug: "second-nature",
    titleKey: "secondNature",
    descriptionKey: "secondNatureDesc",
    bgClass: "bg-[#262626] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "triangles",
    website: "secondnature.ai",
    category: "AI/ML",
  },
  {
    slug: "singular",
    titleKey: "singular",
    descriptionKey: "singularDesc",
    bgClass: "bg-[#666666] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "lines",
    website: "singular.net",
    category: "SaaS",
  },
  {
    slug: "bringg",
    titleKey: "bringg",
    descriptionKey: "bringgDesc",
    bgClass: "bg-[#E5E4DF] text-[#191919] dark:bg-[#40403E] dark:text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "diamond",
    website: "bringg.com",
    category: "Mobility",
  },
  {
    slug: "viz-ai",
    titleKey: "vizAi",
    descriptionKey: "vizAiDesc",
    bgClass: "bg-[#191919] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "circles",
    website: "viz.ai",
    category: "HealthTech",
  },
  {
    slug: "tytocare",
    titleKey: "tytoCare",
    descriptionKey: "tytoCareDesc",
    bgClass: "bg-[#CC785C] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "grid",
    website: "tytocare.com",
    category: "HealthTech",
  },
  {
    slug: "orca-security",
    titleKey: "orcaSecurity",
    descriptionKey: "orcaSecurityDesc",
    bgClass: "bg-[#D4A27F] text-[#191919]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "waves",
    website: "orca.security",
    category: "Cybersecurity",
  },
  {
    slug: "rapyd",
    titleKey: "rapyd",
    descriptionKey: "rapydDesc",
    bgClass: "bg-[#40403E] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "dots",
    website: "rapyd.net",
    category: "Fintech",
  },
  {
    slug: "matia",
    titleKey: "matia",
    descriptionKey: "matiaDesc",
    bgClass: "bg-[#FAFAF7] text-[#191919] border border-black/5 dark:bg-[#262626] dark:text-[#FAFAF7] dark:border-white/5",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "hexagons",
    website: "matia.io",
    category: "AI/ML",
  },
  {
    slug: "legato",
    titleKey: "legato",
    descriptionKey: "legatoDesc",
    bgClass: "bg-[#262626] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "triangles",
    website: "legato.co",
    category: "AI/ML",
  },
  {
    slug: "brandlight",
    titleKey: "brandlight",
    descriptionKey: "brandlightDesc",
    bgClass: "bg-[#666666] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "lines",
    website: "brandlight.org",
    category: "AI/ML",
  },
  {
    slug: "take2",
    titleKey: "take2",
    descriptionKey: "take2Desc",
    bgClass: "bg-[#E5E4DF] text-[#191919] dark:bg-[#40403E] dark:text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "diamond",
    website: "take2.co",
    category: "AI/ML",
  },
  {
    slug: "guidde",
    titleKey: "guidde",
    descriptionKey: "guiddeDesc",
    bgClass: "bg-[#191919] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "circles",
    website: "guidde.com",
    category: "DevTools",
  },
  {
    slug: "similarweb",
    titleKey: "similarWeb",
    descriptionKey: "similarWebDesc",
    bgClass: "bg-[#CC785C] text-[#FAFAF7]",
    icon: "building",
    author: "DocChat",
    date: "Feb 2026",
    sourceCount: 1,
    pattern: "grid",
    website: "similarweb.com",
    category: "SaaS",
  },
];

export function getFeaturedBySlug(slug: string): FeaturedNotebook | undefined {
  return featuredNotebooks.find((fn) => fn.slug === slug);
}
